version: '3.9'
services:
    comfyui:
        build: .
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        ports:
            - 8188:8188
        volumes:
            - ./ComfyUI/models:/usr/local/ComfyUI/models
            - ./ComfyUI/output:/usr/local/ComfyUI/output
            - ./ComfyUI/input:/usr/local/ComfyUI/input
            - ./ComfyUI/custom_nodes:/usr/local/ComfyUI/custom_nodes
